/**
 * i2c_transport.h
 *
 * Abstract I2C transport interface — the HAL boundary TestForge mocks.
 *
 * Real implementation: demo/host/i2c_transport_mpsse.c (uses libftdi1)
 * Mock implementation: generated by testforge generate (no libftdi)
 *
 * © 2026 Myattech LLC. All rights reserved.
 */
#ifndef I2C_TRANSPORT_H
#define I2C_TRANSPORT_H

#include <stdint.h>

typedef struct I2CTransport I2CTransport;

/* Open the FT232H and configure MPSSE for I2C at 100kHz.
 * Returns NULL on failure. Caller frees with i2c_transport_close(). */
I2CTransport* i2c_transport_open(void);

/* Release the transport. Safe to call with NULL. */
void i2c_transport_close(I2CTransport* t);

/* Send I2C START condition. Returns 0 on success, -1 on error. */
int i2c_transport_start(I2CTransport* t);

/* Send I2C STOP condition. Returns 0 on success, -1 on error. */
int i2c_transport_stop(I2CTransport* t);

/* Write one byte. Returns 0 if ACKed, -1 if NAK or timeout. */
int i2c_transport_write_byte(I2CTransport* t, uint8_t byte);

/* Read one byte. ack=1 → send ACK (more bytes follow), ack=0 → send NAK (last byte). */
uint8_t i2c_transport_read_byte(I2CTransport* t, int ack);

/* Returns 1 if the last operation timed out (clock-stretch exceeded limit). */
int i2c_transport_timed_out(I2CTransport* t);

#endif /* I2C_TRANSPORT_H */
