/**
 * pico_i2c_driver.c
 *
 * I2C driver for the Pico 2 W sensor aggregator demo.
 * All hardware I/O goes through i2c_transport.h so this file compiles
 * and is testable without libftdi installed.
 *
 * Real transport: demo/host/i2c_transport_mpsse.c (Phase 2, needs libftdi)
 * Mock transport: generated by testforge generate (Phase 1, no hardware)
 *
 * © 2026 Myattech LLC. All rights reserved.
 */

#include "pico_i2c_driver.h"
#include "i2c_transport.h"
#include <stdlib.h>

/* Struct body — private to this module. Header exposes only the typedef. */
struct PicoI2CHandle {
    I2CTransport* transport;
};

PicoI2CHandle* pico_i2c_open(void) {
    PicoI2CHandle* h = (PicoI2CHandle*)malloc(sizeof(PicoI2CHandle));
    if (!h)
        return NULL;
    h->transport = i2c_transport_open();
    if (!h->transport) {
        free(h);
        return NULL; /* transport unavailable (no hardware) */
    }
    return h;
}

void pico_i2c_close(PicoI2CHandle* handle) {
    if (!handle)
        return;
    /* Save transport before zeroing so we can close and conditionally free.
       transport == NULL means the handle was not heap-allocated by pico_i2c_open
       (e.g. a test stub or already closed) — don't free in that case. */
    I2CTransport* t = handle->transport;
    handle->transport = NULL;
    if (t) {
        i2c_transport_close(t);
        free(handle);
    }
}

PicoI2CStatus pico_i2c_read_register(PicoI2CHandle* handle,
                                      uint8_t        reg,
                                      uint8_t*       out) {
    if (!handle)
        return I2C_ERR_NULL_HANDLE;
    if (!out)
        return I2C_ERR_NULL_HANDLE;
    if (reg > REG_ADDR_MAX)
        return I2C_ERR_ADDR_INVALID;

    I2CTransport* t = handle->transport;

    if (i2c_transport_start(t) < 0)
        return I2C_ERR_IO;
    /* Write phase: address + register pointer */
    if (i2c_transport_write_byte(t, (PICO_I2C_ADDR << 1) | 0x00) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_NAK;
    }
    if (i2c_transport_write_byte(t, reg) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_IO;
    }
    /* Repeated START for read phase */
    if (i2c_transport_start(t) < 0)
        return I2C_ERR_IO;
    if (i2c_transport_write_byte(t, (PICO_I2C_ADDR << 1) | 0x01) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_NAK;
    }

    if (i2c_transport_timed_out(t)) {
        i2c_transport_stop(t);
        return I2C_ERR_TIMEOUT;
    }

    *out = i2c_transport_read_byte(t, 0); /* NAK = last byte */
    i2c_transport_stop(t);

    if (i2c_transport_timed_out(t))
        return I2C_ERR_TIMEOUT;

    return I2C_OK;
}

PicoI2CStatus pico_i2c_write_register(PicoI2CHandle* handle,
                                       uint8_t        reg,
                                       uint8_t        value) {
    if (!handle)
        return I2C_ERR_NULL_HANDLE;
    if (reg > REG_ADDR_MAX)
        return I2C_ERR_ADDR_INVALID;
    /* Read-only registers: 0x00–0x07 */
    if (reg >= REG_ADDR_MIN && reg <= REG_CH2_LO)
        return I2C_ERR_WRITE_DENIED;

    I2CTransport* t = handle->transport;

    if (i2c_transport_start(t) < 0)
        return I2C_ERR_IO;
    if (i2c_transport_write_byte(t, (PICO_I2C_ADDR << 1) | 0x00) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_NAK;
    }
    if (i2c_transport_write_byte(t, reg) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_IO;
    }
    if (i2c_transport_write_byte(t, value) < 0) {
        i2c_transport_stop(t);
        return I2C_ERR_IO;
    }
    i2c_transport_stop(t);
    return I2C_OK;
}

PicoI2CStatus pico_i2c_ping(PicoI2CHandle* handle) {
    if (!handle)
        return I2C_ERR_NULL_HANDLE;
    uint8_t id = 0;
    PicoI2CStatus st = pico_i2c_read_register(handle, REG_DEVICE_ID, &id);
    if (st != I2C_OK)
        return st;
    if (id != EXPECTED_DEVICE_ID)
        return I2C_ERR_NAK;
    return I2C_OK;
}
